### ISSUE TITLE
KB3112336

### ISSUE THREAD

**Issue by v998** [WindowsLies/BlockWindows#32]
https://support.microsoft.com/en-us/kb/3112336

This update **enables support for additional upgrade scenarios from Windows 8.1 to Windows 10**, and provides a smoother experience when you have to retry an operating system upgrade because of certain failure conditions. This update also improves the ability of Microsoft to **monitor the quality of the upgrade experience**.

**Comment by WindowsLies** [comment]
Thanks, now patched
