### ISSUE TITLE
Evaluate KB3146449

### ISSUE THREAD

**Issue by Zurd** [WindowsLies/BlockWindows#41]
https://support.microsoft.com/en-us/kb/3146449

http://tech.slashdot.org/story/16/03/10/1524238/patch-tuesday-brought-windows-10-ad-generator

**Comment by GoToLoop** [comment]
I'm very doubtful whether KB3146449 can be actually removed separately from KB3139929. :worried: 

http://www.InfoWorld.com/article/3042155/microsoft-windows/windows-patch-kb-3139929-when-a-security-update-is-not-a-security-update.html

**Comment by Zurd** [comment]
https://support.microsoft.com/en-us/kb/3139929

Indeed, it cannot be removed separately.

Anyway, the infoworld article says that it adds a blue banner with an ad from Microsoft to upgrade in a new tab but I don't see it even though I have 3139929 installed. I see no ad in Internet Explorer whatsoever.

This story has been blown out of proportion, nothing to do here. I will close this issue.

Thanks!
